#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#5267e280'
TEXT='#5267e2e6'
WRONG='#ff0000ff'
VERIFYING='#00ff00ff'

i3lock \
  --insidever-color=$CLEAR      \
  --ringver-color=$VERIFYING    \
  \
  --insidewrong-color=$CLEAR    \
  --ringwrong-color=$WRONG      \
  \
  --inside-color=$BLANK         \
  --ring-color=$DEFAULT         \
  --line-color=$BLANK           \
  --separator-color=$DEFAULT    \
  \
  --verif-color=$TEXT           \
  --wrong-color=$TEXT           \
  --time-color=$TEXT            \
  --date-color=$TEXT            \
  --layout-color=$TEXT          \
  --keyhl-color=$WRONG          \
  --bshl-color=$WRONG           \
  \
  --screen 1                    \
  --blur 10                     \
  --clock                       \
  --indicator                   \
  --time-str="%H:%M:%S"         \
  --date-str="%A %d"            \
  --keylayout 1                 \
