vo=gpu-next
profile=gpu-hq
gpu-api=vulkan
hwdec=nvdec
hwdec-codecs=all
osc=no
autofit-smaller=100%x100%
autofit-larger=50%x50%

glsl-shader="~~/FSRCNNX_x2_8-0-4-1.glsl"
glsl-shader="~~/SSimSuperRes.glsl"
glsl-shader="~~/SSimDownscaler.glsl"
glsl-shader="~~/KrigBilateral.glsl"

scale=ewa_lanczos
scale-blur=0.981251
cscale=ewa_lanczos
cscale-blur=0.981251
dscale=mitchell
linear-downscaling=no

script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[height<=2160]+bestaudio/best
